extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  
  comments:
    min-spaces-from-content: 1
  
  document-start: disable
  
  brackets:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0
  
  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0