version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      # Watchtower Configuration
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL:-300}  # Check every 5 minutes
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP:-true}
      - WATCHTOWER_INCLUDE_RESTARTING=${WATCHTOWER_INCLUDE_RESTARTING:-true}
      - WATCHTOWER_INCLUDE_STOPPED=${WATCHTOWER_INCLUDE_STOPPED:-false}
      - WATCHTOWER_REVIVE_STOPPED=${WATCHTOWER_REVIVE_STOPPED:-false}
      
      # Rolling Update Configuration
      - WATCHTOWER_ROLLING_RESTART=${WATCHTOWER_ROLLING_RESTART:-true}
      - WATCHTOWER_TIMEOUT=${WATCHTOWER_TIMEOUT:-30s}
      
      # Notification Configuration
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${SLACK_WEBHOOK_URL}
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#deployments
      
      # Monitoring Configuration
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_API_TOKEN}
      
      # Schedule Configuration (optional - use cron format)
      # - WATCHTOWER_SCHEDULE=0 30 4 * * *  # Daily at 4:30 AM
      
      # Debug Configuration
      - WATCHTOWER_DEBUG=${WATCHTOWER_DEBUG:-false}
      - WATCHTOWER_TRACE=${WATCHTOWER_TRACE:-false}
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    
    ports:
      - "8080:8080"  # HTTP API port
    
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Don't update watchtower itself
      - "traefik.enable=false"
    
    command: >
      --interval 300
      --cleanup
      --include-restarting
      --rolling-restart
      --http-api-update
      --http-api-metrics
      --notification-slack-hook-url=${SLACK_WEBHOOK_URL}
      --notification-slack-identifier=watchtower
      --notification-slack-channel=#deployments
      reddit-publisher-api
      reddit-publisher-worker-collector
      reddit-publisher-worker-nlp
      reddit-publisher-worker-publisher
      reddit-publisher-scheduler

  # Watchtower monitoring sidecar
  watchtower-exporter:
    image: prom/node-exporter:latest
    container_name: watchtower-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  default:
    external: true
    name: reddit-publisher-network