"""add_api_keys_table

Revision ID: 3d38506fcf35
Revises: 8d1ab4a331e1
Create Date: 2025-08-06 21:38:11.456740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d38506fcf35'
down_revision: Union[str, None] = '8d1ab4a331e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###