global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@reddit-publisher.com'
  slack_api_url: '${SLACK_WEBHOOK_URL}'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'slack-critical'
    group_wait: 5s
    repeat_interval: 30m
  - match:
      severity: warning
    receiver: 'slack-warning'
    group_wait: 10s
    repeat_interval: 1h
  - match:
      service: reddit-publisher
    receiver: 'slack-reddit-publisher'
    group_wait: 10s
    repeat_interval: 1h

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'slack-critical'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts-critical'
    title: '🚨 Critical Alert - Reddit Publisher'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Service:* {{ .Labels.service }}
      *Status:* {{ .Status }}
      {{ if .Labels.instance }}*Instance:* {{ .Labels.instance }}{{ end }}
      {{ end }}
    send_resolved: true
    title_link: 'http://grafana:3000/alerting/list'
    color: 'danger'

- name: 'slack-warning'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts-warning'
    title: '⚠️ Warning Alert - Reddit Publisher'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Service:* {{ .Labels.service }}
      *Status:* {{ .Status }}
      {{ if .Labels.instance }}*Instance:* {{ .Labels.instance }}{{ end }}
      {{ end }}
    send_resolved: true
    title_link: 'http://grafana:3000/alerting/list'
    color: 'warning'

- name: 'slack-reddit-publisher'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#reddit-publisher-alerts'
    title: '📊 Reddit Publisher Alert'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Service:* {{ .Labels.service }}
      *Status:* {{ .Status }}
      {{ if .Labels.instance }}*Instance:* {{ .Labels.instance }}{{ end }}
      {{ end }}
    send_resolved: true
    title_link: 'http://grafana:3000/alerting/list'
    color: 'good'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']